### ISSUE TITLE
AiNodeEntryGetParameter not returning a proper parameter

### ISSUE THREAD

**Issue by jonahfriedman** [caron/FabricArnold#8]
It seems AiNodeEntryGetParameter may not be working properly and not returning a real parameter. I have the same code in Python and KL here. 

I'll try to look into this later myself, but I figured I'd submit it for now. 

Python version of the code: 
```
from arnold import *
AiBegin()
nodeEntry = AiNodeEntryLookUp("lambert")
paramCount = AiNodeEntryGetNumParams(nodeEntry)
print nodeEntry, paramCount, AiNodeEntryGetName(nodeEntry)
for i in range(0, paramCount):
  pEntry = AiNodeEntryGetParameter(nodeEntry, i)
  pType = AiParamGetType(pEntry)
  print pType
  print AiParamGetTypeName(pType)
  print AiParamGetName(pEntry)
AiEnd()
```
Python output:
```
4
FLOAT
Kd
5
RGB
Kd_color
5
RGB
opacity
10
STRING
aov_direct_diffuse
10
STRING
aov_indirect_diffuse
10
STRING
name
```

KL version of the code: 
```
require FabricArnold;
operator entry() {
  AiBegin();
  AtNodeEntry nodeEntry = AiNodeEntryLookUp("lambert");
  Integer paramCount = AiNodeEntryGetNumParams(nodeEntry);
  for (Size i = 0; i < paramCount; i++) {      
    AtParamEntry pEntry = AiNodeEntryGetParameter(nodeEntry, i); 
    Size paramType = AiParamGetType(pEntry);
    report (paramType);
    report (AiParamGetTypeName( paramType ));
    report (AiParamGetName(pEntry));
  }
  AiEnd();
}
```
KL output:
```
0
BYTE

0
BYTE

0
BYTE

0
BYTE

0
BYTE

0
BYTE
```

**Comment by caron** [comment]
ya, ill look at it too! thanks for testing...

**Comment by caron** [comment]
ok fixed this! i was messing up pointers again and i had some function signatures incorrect.

added a test to the test suite. lets test more of that param entry getter functions in here. there probably are a few more changes need to be made

**Comment by caron** [comment]
hey jonah, have you had a chance to test this?

**Comment by jonahfriedman** [comment]
I just tested it, looks good!

Thanks!
-Jonah

**Comment by jonahfriedman** [comment]
How would you feel about a contribution that allows you access array
members such as nelements and nkeys?

In C++, you can just access these as members, and in python you use
AtArray.contents.nelements to access it. In KL there's no way to do it, so
I've added in c++:

fe_AiArrayGetNElements
fe_AiArrayGetNKeys
fe_AiArrayGetType

And then in KL:

AiArrayGetNElements()
AiArrayGetNKeys()
AiArrayGetType()

and then also in KL just for convenience and nicer code:

AtArray.getNElements()
AtArray.getNKeys()
AtArray.getType()

Unless you think there's a nicer way to do it?
